language: python
before_install:
  - openssl aes-256-cbc -K $encrypted_bd8102ea4c92_key -iv $encrypted_bd8102ea4c92_iv -in id_rsa.enc -out id_rsa -d
  - chmod 600 id_rsa
  - eval $(ssh-agent -s)
  - ssh-add id_rsa

install:
  - pip install -r requirements.txt
script:
  - mkdocs build
deploy:
  skip_cleanup: true
  provider: script
  script: bash $TRAVIS_BUILD_DIR/deploy.sh
  on:
    branch: master
