site_name: Chirripo Docs
site_description: 'Documentation site for Chirripo'
site_author: 'Chirripo'
docs_dir: docs/
repo_name: 'chirripo/dcs'
repo_url: 'https://github.com/chirripo/docs'
nav:
    - Home: index.md
    - Getting Started: getting-started.md
    - Usage: usage.md
    - Commands:
      - Available Commands: commands/index.md
      - db-import: commands/db-import.md
      - docker-compose: commands/docker-compose.md
      - down: commands/down.md
      - drush: commands/drush.md
      - logs: commands/logs.md
      - mysql: commands/mysql.md
      - php-info: commands/php-info.md
      - php-modules: commands/php-modules.md
      - restart: commands/restart.md
      - ssh: commands/ssh.md
      - start: commands/start.md
      - status: commands/status.md
      - stop: commands/stop.md
      - url: commands/url.md
    - Contributing: contributing.md
theme:
  name: 'material'
  language: en
  palette:
    primary: green
    accent: light green
  logo: assets/images/logo.svg
  favicon: assets/images/favicon.ico
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
google_analytics:
  - UA-165331258-2
  - auto
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/chirripo
    - icon: fontawesome/brands/php
      link: https://packagist.org/packages/chirripo/chirripo
