site_name: Chirripo Docs
site_description: 'Documentation site for Chirripo'
site_author: 'Michael Hausenblas'
docs_dir: docs/
repo_name: 'chirripo/dcs'
repo_url: 'https://github.com/chirripo/docs'
nav:
    - Home: index.md
    - Getting Started: getting-started.md
    - Usage: usage.md
    - Commands: commands/index.md
    - Contributing: contributing.md
theme:
  name: 'material'
  language: en
  palette:
    primary: green
    accent: purple
  logo: assets/images/logo.svg
