site_name: Chirripo Docs
site_description: 'Documentation site for Chirripo'
site_author: 'Chirripo'
docs_dir: docs/
repo_name: 'chirripo/dcs'
repo_url: 'https://github.com/chirripo/docs'
nav:
    - Home: index.md
    - Getting Started: getting-started.md
    - Usage: usage.md
    - Commands: commands/index.md
    - Contributing: contributing.md
theme:
  name: 'material'
  language: en
  palette:
    primary: green
    accent: light green
  logo: assets/images/logo.svg
  favicon: assets/images/favicon.ico
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
google_analytics:
  - UA-165331258-2
  - auto
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/chirripo
    - icon: fontawesome/brands/php
      link: https://packagist.org/packages/chirripo/chirripo
